

version: 2

sources:
  - name: dw_proj
    schema: dbfinance
    tables: 
      - name: commodities
        description: "Tabela que contém dados históricos de commodities"
        columns:
          - name: data
            description: "Data da dia dos registros"
          - name: abertura
            description: "Preço de abertura da commodity"
          - name: alta
            description: "Preço de alta da commodity"
          - name: baixa
            description: "Preço de baixa da commodity"
          - name: fechada
            description: "Preço final da commodity"
          - name: simbolo
            description: "Código da commodity"

      - name: movimentacao_commodities
        description: "Tabela seed"
        columns:
          - name: date
            description: "Data da transação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo de transação (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"